# Generated by Django 3.2.6 on 2021-08-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210831_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colorname',
        ),
    ]
