# Generated by Django 3.2.6 on 2021-09-02 07:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=colorfield.fields.ColorField(default='#409EFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=colorfield.fields.ColorField(default='#409EFF', max_length=18),
        ),
    ]
